// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyMigrationSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyMigrationSource'](arg1, arg2, arg3);
}

export function CreateMigration(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMigration'](arg1, arg2, arg3);
}

export function CreateMigrationLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMigrationLink'](arg1, arg2, arg3);
}

export function DeleteMigrationSource(arg1, arg2) {
  return window['go']['main']['App']['DeleteMigrationSource'](arg1, arg2);
}

export function DeleteTrashFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTrashFiles'](arg1, arg2, arg3);
}

export function GetActiveCleaning() {
  return window['go']['main']['App']['GetActiveCleaning']();
}

export function GetDisks() {
  return window['go']['main']['App']['GetDisks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRunningAsAdministrator() {
  return window['go']['main']['App']['IsRunningAsAdministrator']();
}

export function ListCleaningRecords() {
  return window['go']['main']['App']['ListCleaningRecords']();
}

export function ListMigrations() {
  return window['go']['main']['App']['ListMigrations']();
}

export function ListSettings() {
  return window['go']['main']['App']['ListSettings']();
}

export function OpenTrashFileDirectory(arg1) {
  return window['go']['main']['App']['OpenTrashFileDirectory'](arg1);
}

export function RestoreMigration(arg1) {
  return window['go']['main']['App']['RestoreMigration'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMigrationDirectory() {
  return window['go']['main']['App']['SelectMigrationDirectory']();
}

export function StartCleaning(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCleaning'](arg1, arg2, arg3);
}

export function StopCleaning(arg1) {
  return window['go']['main']['App']['StopCleaning'](arg1);
}
