// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {migration} from '../models';
import {cleaner} from '../models';
import {model} from '../models';
import {cleaningrecord} from '../models';
import {setting} from '../models';

export function CopyMigrationSource(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateMigration(arg1:string,arg2:string,arg3:string):Promise<migration.Migration>;

export function CreateMigrationLink(arg1:string,arg2:string,arg3:string):Promise<migration.Migration>;

export function DeleteMigrationSource(arg1:string,arg2:string):Promise<void>;

export function DeleteTrashFiles(arg1:number,arg2:Array<string>,arg3:boolean):Promise<Array<cleaner.DeleteFailure>>;

export function GetActiveCleaning():Promise<cleaner.CleaningTaskSnapshot>;

export function GetDisks():Promise<Array<model.DiskInfo>>;

export function Greet(arg1:string):Promise<string>;

export function IsRunningAsAdministrator():Promise<boolean>;

export function ListCleaningRecords():Promise<Array<cleaningrecord.CleaningRecord>>;

export function ListMigrations():Promise<Array<migration.Migration>>;

export function ListSettings():Promise<Array<setting.Setting>>;

export function OpenTrashFileDirectory(arg1:string):Promise<void>;

export function RestoreMigration(arg1:number):Promise<void>;

export function SaveSettings(arg1:Array<setting.Setting>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectMigrationDirectory():Promise<string>;

export function StartCleaning(arg1:string,arg2:string,arg3:string):Promise<cleaner.CleaningTaskSnapshot>;

export function StopCleaning(arg1:number):Promise<void>;
